In [13]:
import torch
next_token_active =torch.Tensor([2365,1175,1175]).view(3,1)

In [35]:
import torch

next_token_full_batch = torch.tensor([[0],
                                      [0],
                                      [0]], dtype=torch.long)  # shape (3,1)
print(next_token_full_batch)


tensor([[0],
        [0],
        [0]])


In [14]:
next_token_active.shape

torch.Size([3, 1])

In [15]:
next_token_active

tensor([[2365.],
        [1175.],
        [1175.]])

In [17]:
next_token_full_batch

tensor([[0.],
        [0.],
        [0.]])

In [19]:
next_token_active

tensor([[2365.],
        [1175.],
        [1175.]])

In [21]:
next_token_active.squeeze(-1).unsqueeze(-1).shape

torch.Size([3, 1])

In [22]:
next_token_active.squeeze(-1).unsqueeze(-1)

tensor([[2365.],
        [1175.],
        [1175.]])

In [3]:
next_taoken_active

tensor([[ 0.2329],
        [ 1.1632],
        [-0.8730]])

In [24]:
next_token_active

tensor([[2365.],
        [1175.],
        [1175.]])

In [27]:
active_sequences = torch.ones(3, dtype=torch.bool)

In [30]:
active_sequences[0]=False

In [31]:
active_sequences

tensor([False,  True,  True])

In [38]:
next_token_full_batch[active_sequences]=next_token_active.squeeze(-1).unsqueeze(-1)

RuntimeError: shape mismatch: value tensor of shape [3, 1] cannot be broadcast to indexing result of shape [2, 1]

In [ ]:
next_token_logits=tor